TrajectoryPlannerROS:

  holonomic_robot: false
  max_vel_x: 0.7
  min_vel_x: 0.2
  max_vel_theta: 1.0 
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.05
  sim_time: 1.0
  meter_scoring: false
  pdistscale: 0.6
  controller_frequency: 10

